language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux

install:
- sudo apt-get update
- sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
- sudo apt-get install -qq qt57-meta-full

before_script:
- QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
- source $QT_ENV_SCRIPT
 
script:
- qmake BatchGUI.pro -r -spec linux-g++ CONFIG+=release
- make